<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PromiseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromiseRepository extends EntityRepository
{
}
